name: microstock_tools
description: "Adobe Stock Contributor AI Image Tool"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image: ^4.3.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  image_gallery_saver_plus: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
